{{- if and .Values.rbac.enabled .Values.rbac.provisioner.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.provisioner.roleName }}
  namespace: {{ include "vdiforge.namespace.desktops" . }}
  labels:
    {{- include "vdiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
rules:
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
      - virtualmachineinstances
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - cdi.kubevirt.io
    resources:
      - datavolumes
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - services
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.provisioner.roleName }}
  namespace: {{ include "vdiforge.namespace.desktops" . }}
  labels:
    {{- include "vdiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
subjects:
  - kind: ServiceAccount
    name: {{ include "vdiforge.serviceAccount.provisionerName" . }}
    namespace: {{ include "vdiforge.namespace.system" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.provisioner.roleName }}
{{- end }}
