{{- if .Values.resourceGovernance.enabled }}
{{- if .Values.resourceGovernance.quotas.system.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceGovernance.quotas.system.name }}
  namespace: {{ include "vdiforge.namespace.system" . }}
  labels:
    {{- include "vdiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: resource-governance
spec:
  hard:
    {{- toYaml .Values.resourceGovernance.quotas.system.hard | nindent 4 }}
{{- end }}
{{- if and .Values.resourceGovernance.quotas.system.enabled .Values.resourceGovernance.quotas.desktops.enabled }}
---
{{- end }}
{{- if .Values.resourceGovernance.quotas.desktops.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceGovernance.quotas.desktops.name }}
  namespace: {{ include "vdiforge.namespace.desktops" . }}
  labels:
    {{- include "vdiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: resource-governance
spec:
  hard:
    {{- toYaml .Values.resourceGovernance.quotas.desktops.hard | nindent 4 }}
{{- end }}
{{- if and .Values.resourceGovernance.quotas.identity.enabled (or .Values.resourceGovernance.quotas.system.enabled .Values.resourceGovernance.quotas.desktops.enabled) }}
---
{{- end }}
{{- if .Values.resourceGovernance.quotas.identity.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceGovernance.quotas.identity.name }}
  namespace: {{ include "vdiforge.namespace.identity" . }}
  labels:
    {{- include "vdiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: resource-governance
spec:
  hard:
    {{- toYaml .Values.resourceGovernance.quotas.identity.hard | nindent 4 }}
{{- end }}
{{- if and .Values.resourceGovernance.quotas.remoteAccess.enabled (or .Values.resourceGovernance.quotas.system.enabled .Values.resourceGovernance.quotas.desktops.enabled .Values.resourceGovernance.quotas.identity.enabled) }}
---
{{- end }}
{{- if .Values.resourceGovernance.quotas.remoteAccess.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceGovernance.quotas.remoteAccess.name }}
  namespace: {{ include "vdiforge.namespace.remoteAccess" . }}
  labels:
    {{- include "vdiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: resource-governance
spec:
  hard:
    {{- toYaml .Values.resourceGovernance.quotas.remoteAccess.hard | nindent 4 }}
{{- end }}
{{- end }}
