{{- if .Values.serviceAccounts.enabled }}
{{- if .Values.serviceAccounts.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vdiforge.serviceAccount.apiName" . }}
  namespace: {{ include "vdiforge.namespace.system" . }}
  labels:
    {{- include "vdiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
automountServiceAccountToken: {{ .Values.serviceAccounts.api.automountServiceAccountToken }}
{{- end }}
{{- if and .Values.serviceAccounts.api.create .Values.serviceAccounts.provisioner.create }}
---
{{- end }}
{{- if .Values.serviceAccounts.provisioner.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vdiforge.serviceAccount.provisionerName" . }}
  namespace: {{ include "vdiforge.namespace.system" . }}
  labels:
    {{- include "vdiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
automountServiceAccountToken: {{ .Values.serviceAccounts.provisioner.automountServiceAccountToken }}
{{- end }}
{{- if and .Values.serviceAccounts.database.create (or .Values.serviceAccounts.api.create .Values.serviceAccounts.provisioner.create) }}
---
{{- end }}
{{- if .Values.serviceAccounts.database.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vdiforge.serviceAccount.databaseName" . }}
  namespace: {{ include "vdiforge.namespace.system" . }}
  labels:
    {{- include "vdiforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: app-database
automountServiceAccountToken: {{ .Values.serviceAccounts.database.automountServiceAccountToken }}
{{- end }}
{{- end }}
