all:
  vars:
    ansible_user: vdiadmin
    ansible_python_interpreter: /usr/bin/python3
    vdiforge_lab_domain: local
    vdiforge_host_only_subnet: 192.168.56.0/24
    vdiforge_host_only_gateway: 192.168.56.1
  children:
    vdiforge:
      hosts:
        vdi-control-01:
          ansible_host: 192.168.56.10
          vdiforge_role: control-plane
          vdiforge_node_pool: control
        vdi-worker-01:
          ansible_host: 192.168.56.11
          vdiforge_role: platform-worker
          vdiforge_node_pool: platform
        vdi-worker-02:
          ansible_host: 192.168.56.12
          vdiforge_role: vdi-worker
          vdiforge_node_pool: vdi
          vdiforge_nested_virtualization_required: true
    control_plane:
      hosts:
        vdi-control-01:
    platform_workers:
      hosts:
        vdi-worker-01:
    vdi_workers:
      hosts:
        vdi-worker-02:
